export enum LABELS_LIST {
    width = 'Ширина',
    height = 'Высота',
    skf = 'сетка СКФ',
    simple = 'сетка Простая',
    both = 'Общий вид',
    w = 'ширина',
    h = 'высота мин',
    W = 'ширина',
    H = 'высота',
    da = 'дельта А',
    db = 'дельта Б',
    size = 'Размеры (w,h)',
    size_full = 'Размеры (width, height)',
    offset5 = 'Смещение (Тип 5)',
}